<?php

// This file has been auto-generated by the COPS Input\Route class.

$handlers = [
  'html' => 'SebLucas\\Cops\\Handlers\\HtmlHandler',
  'feed' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
  'json' => 'SebLucas\\Cops\\Handlers\\JsonHandler',
  'fetch' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
  'read' => 'SebLucas\\Cops\\Handlers\\ReadHandler',
  'epubfs' => 'SebLucas\\Cops\\Handlers\\EpubFsHandler',
  'restapi' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
  'check' => 'SebLucas\\Cops\\Handlers\\CheckHandler',
  'opds' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
  'loader' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
  'zipper' => 'SebLucas\\Cops\\Handlers\\ZipperHandler',
  'calres' => 'SebLucas\\Cops\\Handlers\\CalResHandler',
  'zipfs' => 'SebLucas\\Cops\\Handlers\\ZipFsHandler',
  'mail' => 'SebLucas\\Cops\\Handlers\\MailHandler',
  'graphql' => 'SebLucas\\Cops\\Handlers\\GraphQLHandler',
  'tables' => 'SebLucas\\Cops\\Handlers\\TableHandler',
  'error' => 'SebLucas\\Cops\\Handlers\\ErrorHandler',
  'phpunit' => 'SebLucas\\Cops\\Handlers\\TestHandler',
];

$static = [
  '/index' => 'page-index',
  '/authors/letter' => 'page-1-letter',
  '/authors' => 'page-authors',
  '/books/letter' => 'page-4-letter',
  '/books/year' => 'page-4-year',
  '/books' => 'page-books',
  '/series' => 'page-series',
  '/typeahead' => 'page-typeahead',
  '/search' => 'page-search',
  '/recent' => 'page-recent',
  '/tags' => 'page-tags',
  '/about' => 'page-about',
  '/languages' => 'page-languages',
  '/customize' => 'page-customize',
  '/publishers' => 'page-publishers',
  '/ratings' => 'page-ratings',
  '/identifiers' => 'page-identifiers',
  '/libraries' => 'page-libraries',
  '/feed/search' => 'feed-search',
  '/feed' => 'feed',
  '/restapi/custom' => 'restapi-customtypes',
  '/restapi/databases' => 'restapi-databases',
  '/restapi/openapi' => 'restapi-openapi',
  '/restapi/routes' => 'restapi-route',
  '/restapi/handlers' => 'restapi-handler',
  '/restapi/notes' => 'restapi-notes',
  '/restapi/preferences' => 'restapi-preferences',
  '/restapi/annotations' => 'restapi-annotations',
  '/restapi/user/details' => 'restapi-user-details',
  '/restapi/user' => 'restapi-user',
  '/check' => 'check',
  '/opds/search' => 'opds-search',
  '/opds' => 'opds',
  '/loader' => 'loader',
  '/mail' => 'mail',
  '/graphql' => 'graphql',
  '/tables' => 'tables',
  '/test' => 'test',
];

$routes = [
  'page-index' => [
    '/index',
    [
      'page' => 'index',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-authors-letter' => [
    '/authors/letter/{id}',
    [
      'page' => '2',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-1-letter' => [
    '/authors/letter',
    [
      'page' => '1',
      'letter' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-author' => [
    '/authors/{id:\\d+}/{title}',
    [
      'page' => '3',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-3-id' => [
    '/authors/{id:\\d+}',
    [
      'page' => '3',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-authors' => [
    '/authors',
    [
      'page' => '1',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-books-letter' => [
    '/books/letter/{id:\\w}',
    [
      'page' => '5',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-4-letter' => [
    '/books/letter',
    [
      'page' => '4',
      'letter' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-books-year' => [
    '/books/year/{id:\\d+}',
    [
      'page' => '50',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-4-year' => [
    '/books/year',
    [
      'page' => '4',
      'year' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-book' => [
    '/books/{id:\\d+}/{author}/{title}',
    [
      'page' => '13',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-13-id' => [
    '/books/{id:\\d+}',
    [
      'page' => '13',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-books' => [
    '/books',
    [
      'page' => '4',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-serie' => [
    '/series/{id:\\d+}/{title}',
    [
      'page' => '7',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-7-id' => [
    '/series/{id:\\d+}',
    [
      'page' => '7',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-series' => [
    '/series',
    [
      'page' => '6',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-typeahead' => [
    '/typeahead',
    [
      'page' => '9',
      'search' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-query-scope' => [
    '/search/{query}/{scope}',
    [
      'page' => '9',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-query' => [
    '/search/{query}',
    [
      'page' => '9',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-search' => [
    '/search',
    [
      'page' => '8',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-recent' => [
    '/recent',
    [
      'page' => '10',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-tag' => [
    '/tags/{id:\\d+}/{title}',
    [
      'page' => '12',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-12-id' => [
    '/tags/{id:\\d+}',
    [
      'page' => '12',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-tags' => [
    '/tags',
    [
      'page' => '11',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-custom' => [
    '/custom/{custom:\\d+}/{id}',
    [
      'page' => '15',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-customtype' => [
    '/custom/{custom:\\d+}',
    [
      'page' => '14',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-about' => [
    '/about',
    [
      'page' => '16',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-language' => [
    '/languages/{id:\\d+}/{title}',
    [
      'page' => '18',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-18-id' => [
    '/languages/{id:\\d+}',
    [
      'page' => '18',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-languages' => [
    '/languages',
    [
      'page' => '17',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-customize' => [
    '/customize',
    [
      'page' => '19',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-publisher' => [
    '/publishers/{id:\\d+}/{title}',
    [
      'page' => '21',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-21-id' => [
    '/publishers/{id:\\d+}',
    [
      'page' => '21',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-publishers' => [
    '/publishers',
    [
      'page' => '20',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-rating' => [
    '/ratings/{id:\\d+}/{title}',
    [
      'page' => '23',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-23-id' => [
    '/ratings/{id:\\d+}',
    [
      'page' => '23',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-ratings' => [
    '/ratings',
    [
      'page' => '22',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-identifier' => [
    '/identifiers/{id:\\w+}/{title}',
    [
      'page' => '42',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-42-id' => [
    '/identifiers/{id:\\w+}',
    [
      'page' => '42',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-identifiers' => [
    '/identifiers',
    [
      'page' => '41',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-libraries' => [
    '/libraries',
    [
      'page' => '43',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed-page-id' => [
    '/feed/{page:\\d+}/{id}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed-search' => [
    '/feed/search',
    [
      'page' => 'search',
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed-page' => [
    '/feed/{page:\\d+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed-path' => [
    '/feed/{path:.+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed' => [
    '/feed',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-file' => [
    '/files/{db:\\d+}/{id:\\d+}/{file:.+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-thumb' => [
    '/thumbs/{db:\\d+}/{id:\\d+}/{thumb}.jpg',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-cover' => [
    '/covers/{db:\\d+}/{id:\\d+}.jpg',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-inline' => [
    '/inline/{db:\\d+}/{data:\\d+}/{ignore}.{type}',
    [
      'view' => 1,
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-data' => [
    '/fetch/{db:\\d+}/{data:\\d+}/{ignore}.{type}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-view' => [
    '/view/{data}/{db}/{ignore}.{type}',
    [
      'view' => 1,
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-download' => [
    '/download/{data}/{db}/{ignore}.{type}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'read-title' => [
    '/read/{db:\\d+}/{data:\\d+}/{title}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ReadHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'read' => [
    '/read/{db:\\d+}/{data:\\d+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ReadHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'epubfs' => [
    '/epubfs/{db:\\d+}/{data:\\d+}/{comp:.+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\EpubFsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-customtypes' => [
    '/restapi/custom',
    [
      '_resource' => 'CustomColumnType',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-database-table' => [
    '/restapi/databases/{db}/{name}',
    [
      '_resource' => 'Database',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-database' => [
    '/restapi/databases/{db}',
    [
      '_resource' => 'Database',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-databases' => [
    '/restapi/databases',
    [
      '_resource' => 'Database',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-openapi' => [
    '/restapi/openapi',
    [
      '_resource' => 'openapi',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-route' => [
    '/restapi/routes',
    [
      '_resource' => 'route',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-handler' => [
    '/restapi/handlers',
    [
      '_resource' => 'handler',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-note' => [
    '/restapi/notes/{type}/{id}/{title}',
    [
      '_resource' => 'Note',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-notes-type-id' => [
    '/restapi/notes/{type}/{id}',
    [
      '_resource' => 'Note',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-notes-type' => [
    '/restapi/notes/{type}',
    [
      '_resource' => 'Note',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-notes' => [
    '/restapi/notes',
    [
      '_resource' => 'Note',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-preference' => [
    '/restapi/preferences/{key}',
    [
      '_resource' => 'Preference',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-preferences' => [
    '/restapi/preferences',
    [
      '_resource' => 'Preference',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-annotation' => [
    '/restapi/annotations/{bookId}/{id}',
    [
      '_resource' => 'Annotation',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-annotations-book' => [
    '/restapi/annotations/{bookId}',
    [
      '_resource' => 'Annotation',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-annotations' => [
    '/restapi/annotations',
    [
      '_resource' => 'Annotation',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-metadata-element-name' => [
    '/restapi/metadata/{bookId}/{element}/{name}',
    [
      '_resource' => 'Metadata',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-metadata-element' => [
    '/restapi/metadata/{bookId}/{element}',
    [
      '_resource' => 'Metadata',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-metadata' => [
    '/restapi/metadata/{bookId}',
    [
      '_resource' => 'Metadata',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-user-details' => [
    '/restapi/user/details',
    [
      '_resource' => 'User',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-user' => [
    '/restapi/user',
    [
      '_resource' => 'User',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-path' => [
    '/restapi/{path:.*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'check-more' => [
    '/check/{more:.*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\CheckHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'check' => [
    '/check',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\CheckHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds-page-id' => [
    '/opds/{page:\\d+}/{id}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds-search' => [
    '/opds/search',
    [
      'page' => 'search',
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds-page' => [
    '/opds/{page:\\d+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds-path' => [
    '/opds/{path:.*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds' => [
    '/opds',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action-dbNum-authorId-urlPath' => [
    '/loader/{action}/{dbNum:\\d+}/{authorId:\\w+}/{urlPath:.*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action-dbNum-authorId' => [
    '/loader/{action}/{dbNum:\\d+}/{authorId:\\w*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action-dbNum' => [
    '/loader/{action}/{dbNum:\\d+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action-' => [
    '/loader/{action}/',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action' => [
    '/loader/{action}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader' => [
    '/loader',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'zipper-page-id-type' => [
    '/zipper/{page}/{id}/{type}.zip',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ZipperHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'zipper-page-type' => [
    '/zipper/{page}/{type}.zip',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ZipperHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'calres' => [
    '/calres/{db:\\d+}/{alg}/{digest}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\CalResHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'zipfs' => [
    '/zipfs/{db:\\d+}/{data:\\d+}/{comp:.+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ZipFsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'mail' => [
    '/mail',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\MailHandler',
    ],
    [
      'POST',
    ],
    [],
  ],
  'graphql' => [
    '/graphql',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\GraphQLHandler',
    ],
    [
      'GET',
      'POST',
    ],
    [],
  ],
  'tables' => [
    '/tables',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\TableHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'test' => [
    '/test',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\TestHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
];

return [
    'handlers' => $handlers,
    'static' => $static,
    'routes' => $routes,
];
