<?php

// This file has been auto-generated by the COPS Input\Route class.

$handlers = [
  'html' => 'SebLucas\\Cops\\Handlers\\HtmlHandler',
  'feed' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
  'json' => 'SebLucas\\Cops\\Handlers\\JsonHandler',
  'fetch' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
  'read' => 'SebLucas\\Cops\\Handlers\\ReadHandler',
  'epubfs' => 'SebLucas\\Cops\\Handlers\\EpubFsHandler',
  'restapi' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
  'check' => 'SebLucas\\Cops\\Handlers\\CheckHandler',
  'opds' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
  'loader' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
  'zipper' => 'SebLucas\\Cops\\Handlers\\ZipperHandler',
  'calres' => 'SebLucas\\Cops\\Handlers\\CalResHandler',
  'zipfs' => 'SebLucas\\Cops\\Handlers\\ZipFsHandler',
  'mail' => 'SebLucas\\Cops\\Handlers\\MailHandler',
  'graphql' => 'SebLucas\\Cops\\Handlers\\GraphQLHandler',
  'tables' => 'SebLucas\\Cops\\Handlers\\TableHandler',
  'error' => 'SebLucas\\Cops\\Handlers\\ErrorHandler',
  'phpunit' => 'SebLucas\\Cops\\Handlers\\TestHandler',
];

$static = [
  '/index' => 'page-index',
  '/authors/letter' => 'page-1-letter',
  '/authors' => 'page-1',
  '/books/letter' => 'page-4-letter',
  '/books/year' => 'page-4-year',
  '/books' => 'page-4',
  '/series' => 'page-6',
  '/search' => 'page-8',
  '/recent' => 'page-10',
  '/tags' => 'page-11',
  '/about' => 'page-16',
  '/languages' => 'page-17',
  '/customize' => 'page-19',
  '/publishers' => 'page-20',
  '/ratings' => 'page-22',
  '/identifiers' => 'page-41',
  '/libraries' => 'page-43',
  '/feed/search' => 'feed-search',
  '/feed' => 'feed',
  '/restapi/custom' => 'restapi-CustomColumnType',
  '/restapi/databases' => 'restapi-Database',
  '/restapi/openapi' => 'restapi-openapi',
  '/restapi/routes' => 'restapi-route',
  '/restapi/handlers' => 'restapi-handler',
  '/restapi/notes' => 'restapi-Note',
  '/restapi/preferences' => 'restapi-Preference',
  '/restapi/annotations' => 'restapi-Annotation',
  '/restapi/user/details' => 'restapi-User-details',
  '/restapi/user' => 'restapi-User',
  '/check' => 'check',
  '/opds/search' => 'opds-search',
  '/opds' => 'opds',
  '/loader' => 'loader',
  '/mail' => 'mail',
  '/graphql' => 'graphql',
  '/tables' => 'tables',
  '/test' => 'test',
];

$routes = [
  'page-index' => [
    '/index',
    [
      'page' => 'index',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-2-id' => [
    '/authors/letter/{id}',
    [
      'page' => '2',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-1-letter' => [
    '/authors/letter',
    [
      'page' => '1',
      'letter' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-3-id-title' => [
    '/authors/{id:\\d+}/{title}',
    [
      'page' => '3',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-3-id' => [
    '/authors/{id:\\d+}',
    [
      'page' => '3',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-1' => [
    '/authors',
    [
      'page' => '1',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-5-id' => [
    '/books/letter/{id:\\w}',
    [
      'page' => '5',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-4-letter' => [
    '/books/letter',
    [
      'page' => '4',
      'letter' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-50-id' => [
    '/books/year/{id:\\d+}',
    [
      'page' => '50',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-4-year' => [
    '/books/year',
    [
      'page' => '4',
      'year' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-13-id-author-title' => [
    '/books/{id:\\d+}/{author}/{title}',
    [
      'page' => '13',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-13-id' => [
    '/books/{id:\\d+}',
    [
      'page' => '13',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-4' => [
    '/books',
    [
      'page' => '4',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-7-id-title' => [
    '/series/{id:\\d+}/{title}',
    [
      'page' => '7',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-7-id' => [
    '/series/{id:\\d+}',
    [
      'page' => '7',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-6' => [
    '/series',
    [
      'page' => '6',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-9-query-scope' => [
    '/query/{query}/{scope}',
    [
      'page' => '9',
      'search' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-9-query' => [
    '/query/{query}',
    [
      'page' => '9',
      'search' => 1,
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-9-search-scope' => [
    '/search/{query}/{scope}',
    [
      'page' => '9',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-9-search' => [
    '/search/{query}',
    [
      'page' => '9',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-8' => [
    '/search',
    [
      'page' => '8',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-10' => [
    '/recent',
    [
      'page' => '10',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-12-id-title' => [
    '/tags/{id:\\d+}/{title}',
    [
      'page' => '12',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-12-id' => [
    '/tags/{id:\\d+}',
    [
      'page' => '12',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-11' => [
    '/tags',
    [
      'page' => '11',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-15-custom-id' => [
    '/custom/{custom:\\d+}/{id}',
    [
      'page' => '15',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-14-custom' => [
    '/custom/{custom:\\d+}',
    [
      'page' => '14',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-16' => [
    '/about',
    [
      'page' => '16',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-18-id-title' => [
    '/languages/{id:\\d+}/{title}',
    [
      'page' => '18',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-18-id' => [
    '/languages/{id:\\d+}',
    [
      'page' => '18',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-17' => [
    '/languages',
    [
      'page' => '17',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-19' => [
    '/customize',
    [
      'page' => '19',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-21-id-title' => [
    '/publishers/{id:\\d+}/{title}',
    [
      'page' => '21',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-21-id' => [
    '/publishers/{id:\\d+}',
    [
      'page' => '21',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-20' => [
    '/publishers',
    [
      'page' => '20',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-23-id-title' => [
    '/ratings/{id:\\d+}/{title}',
    [
      'page' => '23',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-23-id' => [
    '/ratings/{id:\\d+}',
    [
      'page' => '23',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-22' => [
    '/ratings',
    [
      'page' => '22',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-42-id-title' => [
    '/identifiers/{id:\\w+}/{title}',
    [
      'page' => '42',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-42-id' => [
    '/identifiers/{id:\\w+}',
    [
      'page' => '42',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-41' => [
    '/identifiers',
    [
      'page' => '41',
    ],
    [
      'GET',
    ],
    [],
  ],
  'page-43' => [
    '/libraries',
    [
      'page' => '43',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed-page-id' => [
    '/feed/{page}/{id}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed-search' => [
    '/feed/search',
    [
      'page' => 'search',
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed-page' => [
    '/feed/{page}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'feed' => [
    '/feed',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FeedHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-file' => [
    '/files/{db:\\d+}/{id:\\d+}/{file:.+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-thumb' => [
    '/thumbs/{db:\\d+}/{id:\\d+}/{thumb}.jpg',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-cover' => [
    '/covers/{db:\\d+}/{id:\\d+}.jpg',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-inline' => [
    '/inline/{db:\\d+}/{data:\\d+}/{ignore}.{type}',
    [
      'view' => 1,
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-data' => [
    '/fetch/{db:\\d+}/{data:\\d+}/{ignore}.{type}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-view' => [
    '/view/{data}/{db}/{ignore}.{type}',
    [
      'view' => 1,
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'fetch-download' => [
    '/download/{data}/{db}/{ignore}.{type}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\FetchHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'read-title' => [
    '/read/{db:\\d+}/{data:\\d+}/{title}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ReadHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'read' => [
    '/read/{db:\\d+}/{data:\\d+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ReadHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'epubfs' => [
    '/epubfs/{db:\\d+}/{data:\\d+}/{comp:.+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\EpubFsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-CustomColumnType' => [
    '/restapi/custom',
    [
      '_resource' => 'CustomColumnType',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Database-db-name' => [
    '/restapi/databases/{db}/{name}',
    [
      '_resource' => 'Database',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Database-db' => [
    '/restapi/databases/{db}',
    [
      '_resource' => 'Database',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Database' => [
    '/restapi/databases',
    [
      '_resource' => 'Database',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-openapi' => [
    '/restapi/openapi',
    [
      '_resource' => 'openapi',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-route' => [
    '/restapi/routes',
    [
      '_resource' => 'route',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-handler' => [
    '/restapi/handlers',
    [
      '_resource' => 'handler',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Note-type-id-title' => [
    '/restapi/notes/{type}/{id}/{title}',
    [
      '_resource' => 'Note',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Note-type-id' => [
    '/restapi/notes/{type}/{id}',
    [
      '_resource' => 'Note',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Note-type' => [
    '/restapi/notes/{type}',
    [
      '_resource' => 'Note',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Note' => [
    '/restapi/notes',
    [
      '_resource' => 'Note',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Preference-key' => [
    '/restapi/preferences/{key}',
    [
      '_resource' => 'Preference',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Preference' => [
    '/restapi/preferences',
    [
      '_resource' => 'Preference',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Annotation-bookId-id' => [
    '/restapi/annotations/{bookId}/{id}',
    [
      '_resource' => 'Annotation',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Annotation-bookId' => [
    '/restapi/annotations/{bookId}',
    [
      '_resource' => 'Annotation',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Annotation' => [
    '/restapi/annotations',
    [
      '_resource' => 'Annotation',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Metadata-bookId-element-name' => [
    '/restapi/metadata/{bookId}/{element}/{name}',
    [
      '_resource' => 'Metadata',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Metadata-bookId-element' => [
    '/restapi/metadata/{bookId}/{element}',
    [
      '_resource' => 'Metadata',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-Metadata-bookId' => [
    '/restapi/metadata/{bookId}',
    [
      '_resource' => 'Metadata',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-User-details' => [
    '/restapi/user/details',
    [
      '_resource' => 'User',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-User' => [
    '/restapi/user',
    [
      '_resource' => 'User',
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'restapi-other' => [
    '/restapi/{route:.*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\RestApiHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'check-more' => [
    '/check/{more:.*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\CheckHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'check' => [
    '/check',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\CheckHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds-page-id' => [
    '/opds/{page}/{id}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds-search' => [
    '/opds/search',
    [
      'page' => 'search',
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds-page' => [
    '/opds/{page}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'opds' => [
    '/opds',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\OpdsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action-dbNum-authorId-urlPath' => [
    '/loader/{action}/{dbNum:\\d+}/{authorId:\\w+}/{urlPath:.*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action-dbNum-authorId' => [
    '/loader/{action}/{dbNum:\\d+}/{authorId:\\w*}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action-dbNum' => [
    '/loader/{action}/{dbNum:\\d+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action-' => [
    '/loader/{action}/',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader-action' => [
    '/loader/{action}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'loader' => [
    '/loader',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\LoaderHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'zipper-page-id-type' => [
    '/zipper/{page}/{id}/{type}.zip',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ZipperHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'zipper-page-type' => [
    '/zipper/{page}/{type}.zip',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ZipperHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'calres' => [
    '/calres/{db:\\d+}/{alg}/{digest}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\CalResHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'zipfs' => [
    '/zipfs/{db:\\d+}/{data:\\d+}/{comp:.+}',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\ZipFsHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'mail' => [
    '/mail',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\MailHandler',
    ],
    [
      'POST',
    ],
    [],
  ],
  'graphql' => [
    '/graphql',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\GraphQLHandler',
    ],
    [
      'GET',
      'POST',
    ],
    [],
  ],
  'tables' => [
    '/tables',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\TableHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
  'test' => [
    '/test',
    [
      '_handler' => 'SebLucas\\Cops\\Handlers\\TestHandler',
    ],
    [
      'GET',
    ],
    [],
  ],
];

return [
    'handlers' => $handlers,
    'static' => $static,
    'routes' => $routes,
];
